"""create initial tables

Revision ID: 5df492a465b6
Revises: 
Create Date: 2026-06-10 14:47:22.859665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df492a465b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='管理者ユーザーID'),
    sa.Column('username', sa.String(), nullable=False, comment='管理者のユーザー名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False, comment='会議室ID'),
    sa.Column('manager_id', sa.Integer(), nullable=False, comment='管理ユーザーID'),
    sa.Column('room_name', sa.String(), nullable=False, comment='会議室名'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='収容人数'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_name'), 'rooms', ['room_name'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False, comment='予約ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='予約ユーザーID'),
    sa.Column('room_id', sa.Integer(), nullable=False, comment='会議室ID'),
    sa.Column('reserved_num', sa.Integer(), nullable=False, comment='参加人数'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False, comment='開始時刻'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='終了時刻'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_end_at'), 'bookings', ['end_at'], unique=False)
    op.create_index(op.f('ix_bookings_room_id'), 'bookings', ['room_id'], unique=False)
    op.create_index(op.f('ix_bookings_start_at'), 'bookings', ['start_at'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_room_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_end_at'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_rooms_room_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
